OPENPOSE_KEYPOINTS = {
    "nose": [0,0,0],
    "r_eye": [0,0,0],
    "r_ear": [0,0,0],
    "l_eye": [0,0,0],
    "l_ear": [0,0,0],
    "neck": [0,0,0],
    "r_shoulder": [0,0,0],
    "r_elbow": [0,0,0],
    "r_wrist": [0,0,0],
    "l_shoulder": [0,0,0],
    "l_elbow": [0,0,0],
    "l_wrist": [0,0,0],
    "r_hip": [0,0,0],
    "r_knee": [0,0,0],
    "r_ankle": [0,0,0],
    "l_hip": [0,0,0],
    "l_knee": [0,0,0],
    "l_ankle": [0,0,0],
    "r_thumb_trapezium": [0,0,0],
    "r_thumb_metacarpal": [0,0,0],
    "r_thumb_proximal": [0,0,0],
    "r_thumb_distal": [0,0,0],
    "r_index_metacarpal": [0,0,0],
    "r_index_proximal": [0,0,0],
    "r_index_middle": [0,0,0],
    "r_index_distal": [0,0,0],
    "r_middle_metacarpal": [0,0,0],
    "r_middle_proximal": [0,0,0],
    "r_middle_middle": [0,0,0],
    "r_middle_distal": [0,0,0],
    "r_ring_metacarpal": [0,0,0],
    "r_ring_proximal": [0,0,0],
    "r_ring_middle": [0,0,0],
    "r_ring_distal": [0,0,0],
    "r_pinky_metacarpal": [0,0,0],
    "r_pinky_proximal": [0,0,0],
    "r_pinky_middle": [0,0,0],
    "r_pinky_distal": [0,0,0],
    "l_thumb_trapezium": [0,0,0],
    "l_thumb_metacarpal": [0,0,0],
    "l_thumb_proximal": [0,0,0],
    "l_thumb_distal": [0,0,0],
    "l_index_metacarpal": [0,0,0],
    "l_index_proximal": [0,0,0],
    "l_index_middle": [0,0,0],
    "l_index_distal": [0,0,0],
    "l_middle_metacarpal": [0,0,0],
    "l_middle_proximal": [0,0,0],
    "l_middle_middle": [0,0,0],
    "l_middle_distal": [0,0,0],
    "l_ring_metacarpal": [0,0,0],
    "l_ring_proximal": [0,0,0],
    "l_ring_middle": [0,0,0],
    "l_ring_distal": [0,0,0],
    "l_pinky_metacarpal": [0,0,0],
    "l_pinky_proximal": [0,0,0],
    "l_pinky_middle": [0,0,0],
    "l_pinky_distal": [0,0,0]
}

OPENPOSE_RELATIONS = {
    "nose-r_eye": ["nose","r_eye"],
    "r_eye-r_ear": ["r_eye","r_ear"],
    "nose-l_eye": ["nose","l_eye"],
    "l_eye-l_ear": ["l_eye","l_ear"],
    "nose-neck": ["nose","neck"],
    "neck-r_shoulder": ["neck","r_shoulder"],
    "r_shoulder-r_elbow": ["r_shoulder","r_elbow"],
    "r_elbow-r_wrist": ["r_elbow","r_wrist"],
    "neck-l_shoulder": ["neck","l_shoulder"],
    "l_shoulder-l_elbow": ["l_shoulder","l_elbow"],
    "l_elbow-l_wrist": ["l_elbow","l_wrist"],
    "neck-r_hip": ["neck","r_hip"],
    "r_hip-r_knee": ["r_hip","r_knee"],
    "r_knee-r_ankle": ["r_knee","r_ankle"],
    "neck-l_hip": ["neck","l_hip"],
    "l_hip-l_knee": ["l_hip","l_knee"],
    "l_knee-l_ankle": ["l_knee","l_ankle"],
    "r_wrist-r_thumb_trapezium": ["r_wrist","r_thumb_trapezium"],
    "r_thumb_trapezium-r_thumb_metacarpal": ["r_thumb_trapezium","r_thumb_metacarpal"],
    "r_thumb_metacarpal-r_thumb_proximal": ["r_thumb_metacarpal","r_thumb_proximal"],
    "r_thumb_proximal-r_thumb_distal": ["r_thumb_proximal","r_thumb_distal"],
    "r_wrist-r_index_metacarpal": ["r_wrist","r_index_metacarpal"],
    "r_index_metacarpal-r_index_proximal": ["r_index_metacarpal","r_index_proximal"],
    "r_index_proximal-r_index_middle": ["r_index_proximal","r_index_middle"],
    "r_index_middle-r_index_distal": ["r_index_middle","r_index_distal"],
    "r_wrist-r_middle_metacarpal": ["r_wrist","r_middle_metacarpal"],
    "r_middle_metacarpal-r_middle_proximal": ["r_middle_metacarpal","r_middle_proximal"],
    "r_middle_proximal-r_middle_middle": ["r_middle_proximal","r_middle_middle"],
    "r_middle_middle-r_middle_distal": ["r_middle_middle","r_middle_distal"],
    "r_wrist-r_ring_metacarpal": ["r_wrist","r_ring_metacarpal"],
    "r_ring_metacarpal-r_ring_proximal": ["r_ring_metacarpal","r_ring_proximal"],
    "r_ring_proximal-r_ring_middle": ["r_ring_proximal","r_ring_middle"],
    "r_ring_middle-r_ring_distal": ["r_ring_middle","r_ring_distal"],
    "r_wrist-r_pinky_metacarpal": ["r_wrist","r_pinky_metacarpal"],
    "r_pinky_metacarpal-r_pinky_proximal": ["r_pinky_metacarpal","r_pinky_proximal"],
    "r_pinky_proximal-r_pinky_middle": ["r_pinky_proximal","r_pinky_middle"],
    "r_pinky_middle-r_pinky_distal": ["r_pinky_middle","r_pinky_distal"],
    "l_wrist-l_thumb_trapezium": ["l_wrist","l_thumb_trapezium"],
    "l_thumb_trapezium-l_thumb_metacarpal": ["l_thumb_trapezium","l_thumb_metacarpal"],
    "l_thumb_metacarpal-l_thumb_proximal": ["l_thumb_metacarpal","l_thumb_proximal"],
    "l_thumb_proximal-l_thumb_distal": ["l_thumb_proximal","l_thumb_distal"],
    "l_wrist-l_index_metacarpal": ["l_wrist","l_index_metacarpal"],
    "l_index_metacarpal-l_index_proximal": ["l_index_metacarpal","l_index_proximal"],
    "l_index_proximal-l_index_middle": ["l_index_proximal","l_index_middle"],
    "l_index_middle-l_index_distal": ["l_index_middle","l_index_distal"],
    "l_wrist-l_middle_metacarpal": ["l_wrist","l_middle_metacarpal"],
    "l_middle_metacarpal-l_middle_proximal": ["l_middle_metacarpal","l_middle_proximal"],
    "l_middle_proximal-l_middle_middle": ["l_middle_proximal","l_middle_middle"],
    "l_middle_middle-l_middle_distal": ["l_middle_middle","l_middle_distal"],
    "l_wrist-l_ring_metacarpal": ["l_wrist","l_ring_metacarpal"],
    "l_ring_metacarpal-l_ring_proximal": ["l_ring_metacarpal","l_ring_proximal"],
    "l_ring_proximal-l_ring_middle": ["l_ring_proximal","l_ring_middle"],
    "l_ring_middle-l_ring_distal": ["l_ring_middle","l_ring_distal"],
    "l_wrist-l_pinky_metacarpal": ["l_wrist","l_pinky_metacarpal"],
    "l_pinky_metacarpal-l_pinky_proximal": ["l_pinky_metacarpal","l_pinky_proximal"],
    "l_pinky_proximal-l_pinky_middle": ["l_pinky_proximal","l_pinky_middle"],
    "l_pinky_middle-l_pinky_distal": ["l_pinky_middle","l_pinky_distal"]
}

RENDER_ORDER = [
    "nose-r_eye",
    "r_eye-r_ear",
    "nose-l_eye",
    "l_eye-l_ear",
    "nose-neck",
    "neck-r_shoulder",
    "r_shoulder-r_elbow",
    "r_elbow-r_wrist",
    "neck-l_shoulder",
    "l_shoulder-l_elbow",
    "l_elbow-l_wrist",
    "neck-r_hip",
    "r_hip-r_knee",
    "r_knee-r_ankle",
    "neck-l_hip",
    "l_hip-l_knee",
    "l_knee-l_ankle",
    "r_wrist-r_thumb_trapezium",
    "r_thumb_trapezium-r_thumb_metacarpal",
    "r_thumb_metacarpal-r_thumb_proximal",
    "r_thumb_proximal-r_thumb_distal",
    "r_wrist-r_index_metacarpal",
    "r_index_metacarpal-r_index_proximal",
    "r_index_proximal-r_index_middle",
    "r_index_middle-r_index_distal",
    "r_wrist-r_middle_metacarpal",
    "r_middle_metacarpal-r_middle_proximal",
    "r_middle_proximal-r_middle_middle",
    "r_middle_middle-r_middle_distal",
    "r_wrist-r_ring_metacarpal",
    "r_ring_metacarpal-r_ring_proximal",
    "r_ring_proximal-r_ring_middle",
    "r_ring_middle-r_ring_distal",
    "r_wrist-r_pinky_metacarpal",
    "r_pinky_metacarpal-r_pinky_proximal",
    "r_pinky_proximal-r_pinky_middle",
    "r_pinky_middle-r_pinky_distal",
    "l_wrist-l_thumb_trapezium",
    "l_thumb_trapezium-l_thumb_metacarpal",
    "l_thumb_metacarpal-l_thumb_proximal",
    "l_thumb_proximal-l_thumb_distal",
    "l_wrist-l_index_metacarpal",
    "l_index_metacarpal-l_index_proximal",
    "l_index_proximal-l_index_middle",
    "l_index_middle-l_index_distal",
    "l_wrist-l_middle_metacarpal",
    "l_middle_metacarpal-l_middle_proximal",
    "l_middle_proximal-l_middle_middle",
    "l_middle_middle-l_middle_distal",
    "l_wrist-l_ring_metacarpal",
    "l_ring_metacarpal-l_ring_proximal",
    "l_ring_proximal-l_ring_middle",
    "l_ring_middle-l_ring_distal",
    "l_wrist-l_pinky_metacarpal",
    "l_pinky_metacarpal-l_pinky_proximal",
    "l_pinky_proximal-l_pinky_middle",
    "l_pinky_middle-l_pinky_distal",
    "nose",
    "r_eye",
    "r_ear",
    "l_eye",
    "l_ear",
    "neck",
    "r_shoulder",
    "r_elbow",
    "r_wrist",
    "l_shoulder",
    "l_elbow",
    "l_wrist",
    "r_hip",
    "r_knee",
    "r_ankle",
    "l_hip",
    "l_knee",
    "l_ankle",
    "r_thumb_trapezium",
    "r_thumb_metacarpal",
    "r_thumb_proximal",
    "r_thumb_distal",
    "r_index_metacarpal",
    "r_index_proximal",
    "r_index_middle",
    "r_index_distal",
    "r_middle_metacarpal",
    "r_middle_proximal",
    "r_middle_middle",
    "r_middle_distal",
    "r_ring_metacarpal",
    "r_ring_proximal",
    "r_ring_middle",
    "r_ring_distal",
    "r_pinky_metacarpal",
    "r_pinky_proximal",
    "r_pinky_middle",
    "r_pinky_distal",
    "l_thumb_trapezium",
    "l_thumb_metacarpal",
    "l_thumb_proximal",
    "l_thumb_distal",
    "l_index_metacarpal",
    "l_index_proximal",
    "l_index_middle",
    "l_index_distal",
    "l_middle_metacarpal",
    "l_middle_proximal",
    "l_middle_middle",
    "l_middle_distal",
    "l_ring_metacarpal",
    "l_ring_proximal",
    "l_ring_middle",
    "l_ring_distal",
    "l_pinky_metacarpal",
    "l_pinky_proximal",
    "l_pinky_middle",
    "l_pinky_distal"
]

KEYPOINT_COLORS = {
    "nose": [255,0,0],
    "r_eye": [170,0,255],
    "r_ear": [255,0,170],
    "l_eye": [255,0,255],
    "l_ear": [255,0,85],
    "neck": [255,85,0],
    "r_shoulder": [255,170,0],
    "r_elbow": [255,255,0],
    "r_wrist": [170,255,0],
    "l_shoulder": [85,255,0],
    "l_elbow": [0,255,0],
    "l_wrist": [0,255,85],
    "r_hip": [0,255,170],
    "r_knee": [0,255,255],
    "r_ankle": [0,170,255],
    "l_hip": [0,85,255],
    "l_knee": [0,0,255],
    "l_ankle": [85,0,255],
    "r_thumb_trapezium": [0,0,255],
    "r_thumb_metacarpal": [0,0,255],
    "r_thumb_proximal": [0,0,255],
    "r_thumb_distal": [0,0,255],
    "r_index_metacarpal": [0,0,255],
    "r_index_proximal": [0,0,255],
    "r_index_middle": [0,0,255],
    "r_index_distal": [0,0,255],
    "r_middle_metacarpal": [0,0,255],
    "r_middle_proximal": [0,0,255],
    "r_middle_middle": [0,0,255],
    "r_middle_distal": [0,0,255],
    "r_ring_metacarpal": [0,0,255],
    "r_ring_proximal": [0,0,255],
    "r_ring_middle": [0,0,255],
    "r_ring_distal": [0,0,255],
    "r_pinky_metacarpal": [0,0,255],
    "r_pinky_proximal": [0,0,255],
    "r_pinky_middle": [0,0,255],
    "r_pinky_distal": [0,0,255],
    "l_thumb_trapezium": [0,0,255],
    "l_thumb_metacarpal": [0,0,255],
    "l_thumb_proximal": [0,0,255],
    "l_thumb_distal": [0,0,255],
    "l_index_metacarpal": [0,0,255],
    "l_index_proximal": [0,0,255],
    "l_index_middle": [0,0,255],
    "l_index_distal": [0,0,255],
    "l_middle_metacarpal": [0,0,255],
    "l_middle_proximal": [0,0,255],
    "l_middle_middle": [0,0,255],
    "l_middle_distal": [0,0,255],
    "l_ring_metacarpal": [0,0,255],
    "l_ring_proximal": [0,0,255],
    "l_ring_middle": [0,0,255],
    "l_ring_distal": [0,0,255],
    "l_pinky_metacarpal": [0,0,255],
    "l_pinky_proximal": [0,0,255],
    "l_pinky_middle": [0,0,255],
    "l_pinky_distal": [0,0,255]
}

RELATION_COLORS = {
    "nose-r_eye": [51,0,153],
    "r_eye-r_ear": [102,0,153],
    "nose-l_eye": [153,0,153],
    "l_eye-l_ear": [153,0,103],
    "nose-neck": [0,0,153],
    "neck-r_shoulder": [153,0,0],
    "r_shoulder-r_elbow": [153,102,0],
    "r_elbow-r_wrist": [153,153,0],
    "neck-l_shoulder": [153,51,0],
    "l_shoulder-l_elbow": [102,153,0],
    "l_elbow-l_wrist": [51,153,0],
    "neck-r_hip": [0,153,0],
    "r_hip-r_knee": [0,153,51],
    "r_knee-r_ankle": [0,153,102],
    "neck-l_hip": [0,153,153],
    "l_hip-l_knee": [0,102,153],
    "l_knee-l_ankle": [0,51,153],
    "r_wrist-r_thumb_trapezium": [255,0,0],
    "r_thumb_trapezium-r_thumb_metacarpal": [255,77,0],
    "r_thumb_metacarpal-r_thumb_proximal": [255,153,0],
    "r_thumb_proximal-r_thumb_distal": [255,229,0],
    "r_wrist-r_index_metacarpal": [204,255,0],
    "r_index_metacarpal-r_index_proximal": [128,255,0],
    "r_index_proximal-r_index_middle": [51,255,0],
    "r_index_middle-r_index_distal": [0,255,25],
    "r_wrist-r_middle_metacarpal": [0,255,102],
    "r_middle_metacarpal-r_middle_proximal": [0,255,179],
    "r_middle_proximal-r_middle_middle": [0,255,255],
    "r_middle_middle-r_middle_distal": [0,178,255],
    "r_wrist-r_ring_metacarpal": [0,102,255],
    "r_ring_metacarpal-r_ring_proximal": [0,25,255],
    "r_ring_proximal-r_ring_middle": [51,0,255],
    "r_ring_middle-r_ring_distal": [128,0,255],
    "r_wrist-r_pinky_metacarpal": [204,0,255],
    "r_pinky_metacarpal-r_pinky_proximal": [255,0,230],
    "r_pinky_proximal-r_pinky_middle": [255,0,153],
    "r_pinky_middle-r_pinky_distal": [255,0,77],
    "l_wrist-l_thumb_trapezium": [255,0,0],
    "l_thumb_trapezium-l_thumb_metacarpal": [255,77,0],
    "l_thumb_metacarpal-l_thumb_proximal": [255,153,0],
    "l_thumb_proximal-l_thumb_distal": [255,229,0],
    "l_wrist-l_index_metacarpal": [204,255,0],
    "l_index_metacarpal-l_index_proximal": [128,255,0],
    "l_index_proximal-l_index_middle": [51,255,0],
    "l_index_middle-l_index_distal": [0,255,25],
    "l_wrist-l_middle_metacarpal": [0,255,102],
    "l_middle_metacarpal-l_middle_proximal": [0,255,179],
    "l_middle_proximal-l_middle_middle": [0,255,255],
    "l_middle_middle-l_middle_distal": [0,178,255],
    "l_wrist-l_ring_metacarpal": [0,102,255],
    "l_ring_metacarpal-l_ring_proximal": [0,25,255],
    "l_ring_proximal-l_ring_middle": [51,0,255],
    "l_ring_middle-l_ring_distal": [128,0,255],
    "l_wrist-l_pinky_metacarpal": [204,0,255],
    "l_pinky_metacarpal-l_pinky_proximal": [255,0,230],
    "l_pinky_proximal-l_pinky_middle": [255,0,153],
    "l_pinky_middle-l_pinky_distal": [255,0,77]
}

R_HAND_LANDMARKS = {
    "r_thumb_trapezium",
    "r_thumb_metacarpal",
    "r_thumb_proximal",
    "r_thumb_distal",
    "r_index_metacarpal",
    "r_index_proximal",
    "r_index_middle",
    "r_index_distal",
    "r_middle_metacarpal",
    "r_middle_proximal",
    "r_middle_middle",
    "r_middle_distal",
    "r_ring_metacarpal",
    "r_ring_proximal",
    "r_ring_middle",
    "r_ring_distal",
    "r_pinky_metacarpal",
    "r_pinky_proximal",
    "r_pinky_middle",
    "r_pinky_distal"
}

L_HAND_LANDMARKS = {
    "l_thumb_trapezium",
    "l_thumb_metacarpal",
    "l_thumb_proximal",
    "l_thumb_distal",
    "l_index_metacarpal",
    "l_index_proximal",
    "l_index_middle",
    "l_index_distal",
    "l_middle_metacarpal",
    "l_middle_proximal",
    "l_middle_middle",
    "l_middle_distal",
    "l_ring_metacarpal",
    "l_ring_proximal",
    "l_ring_middle",
    "l_ring_distal",
    "l_pinky_metacarpal",
    "l_pinky_proximal",
    "l_pinky_middle",
    "l_pinky_distal"
}